### ISSUE TITLE
require 'racc' after require 'racc/parser' will raise error

### ISSUE THREAD

**Issue by windwiny** [tenderlove/racc#74]
@alexdowad
 install racc dev version `3f492b8` and run `require"racc/parser"; require"racc"` will raise error

```
$ gem list racc
*** LOCAL GEMS ***
racc (1.4.13)

$ racc --version
racc 2.0.0-dev, codename: Mecha Oishii (c core)

$ ruby -e 'p require"racc"; p require"racc/parser"; p "end" '
true
false
"end"

$ ruby -e 'p require"racc/parser"; p require"racc"; p "end" '
true
/usr/local/ruby_trunk/lib/ruby/gems/2.3.0/gems/racc-1.4.13/lib/racc/exception.rb:11:in `<module:Racc>': superclass mismatch for class ParseError (TypeError)
    from /usr/local/ruby_trunk/lib/ruby/gems/2.3.0/gems/racc-1.4.13/lib/racc/exception.rb:8:in `<top (required)>'
    from /usr/local/ruby_trunk/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/ruby_trunk/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/ruby_trunk/lib/ruby/gems/2.3.0/gems/racc-1.4.13/lib/racc/grammar.rb:9:in `<top (required)>'
    from /usr/local/ruby_trunk/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/ruby_trunk/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/ruby_trunk/lib/ruby/gems/2.3.0/gems/racc-1.4.13/lib/racc.rb:1:in `<top (required)>'
    from /usr/local/ruby_trunk/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /usr/local/ruby_trunk/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /usr/local/ruby_trunk/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from -e:1:in `<main>'

```

**Comment by alexdowad** [comment]
Works fine for me on current `HEAD`:

```
18:50 ~prog/Ruby/racc % ruby -Ilib -e 'p require"racc/parser"; p require"racc"; p "end" '
true
true
"end"
```
